name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  supabase-functions-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Type-check edge functions
        run: deno check supabase/functions/generate_scenario/index.ts supabase/functions/score_answer/index.ts
      - name: Lint
        run: deno lint

