name: Expo Publish (staging)

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        working-directory: apps/mobile
        run: npm ci
      - name: Login to Expo
        env:
          EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: npx expo whoami || npx expo login --token "$EXPO_TOKEN"
      - name: Publish to staging (Expo Go)
        working-directory: apps/mobile
        env:
          EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
        run: npx expo publish --non-interactive --release-channel staging

